"""
pdf_labels.py
=============
Static PDF chrome (headings, field labels, the closed set of human-readable
status words) pre-translated into every language the app-wide switcher
supports -- deterministic, not LLM-translated, exactly like the frontend's
locales/*.json. Case names, citation strings, section numbers, court names,
and dates are never translated anywhere in this app and are not covered here.

Used by routes/citations.py's PDF export so "generate the report in my
language" also covers the PDF, not just the on-screen view.
"""

_EN = {
    "title": "Citation Integrity Report",
    "summary_verified": "Verified",
    "summary_partial": "Partial Match",
    "summary_mismatch": "Mismatch",
    "summary_fabrication": "Fabrication",
    "summary_unverified": "Unverified",
    "full_filing_text": "Full Filing Text",
    "citations_found": "Citations Found in This Filing",
    "court": "Court",
    "date": "Date",
    "status": "Status",
    "identity": "Identity",
    "proposition": "Proposition",
    "na": "N/A",
    "adjusted_note": "* Adjusted from prior human correction",
    "originally": "originally",
    "status_Verified": "Verified",
    "status_Partial Match": "Partial Match",
    "status_Mismatch": "Mismatch",
    "status_Possible Fabrication": "Possible Fabrication",
    "status_Unverified Citation": "Unverified Citation",
    "status_External Source Error": "External Source Error",
    "status_Not Indexed / Not Found": "Not Indexed / Not Found",
}

PDF_LABELS = {
    "en": _EN,
    "hindi": {
        "title": "उद्धरण अखंडता रिपोर्ट",
        "summary_verified": "सत्यापित",
        "summary_partial": "आंशिक मेल",
        "summary_mismatch": "बेमेल",
        "summary_fabrication": "मनगढ़ंत",
        "summary_unverified": "असत्यापित",
        "full_filing_text": "पूर्ण फाइलिंग पाठ",
        "citations_found": "इस फाइलिंग में पाए गए उद्धरण",
        "court": "न्यायालय",
        "date": "तिथि",
        "status": "स्थिति",
        "identity": "पहचान",
        "proposition": "कथन",
        "na": "उपलब्ध नहीं",
        "adjusted_note": "* पूर्व मानव सुधार से समायोजित",
        "originally": "मूल रूप से",
        "status_Verified": "सत्यापित",
        "status_Partial Match": "आंशिक मेल",
        "status_Mismatch": "बेमेल",
        "status_Possible Fabrication": "संभावित मनगढ़ंत",
        "status_Unverified Citation": "असत्यापित उद्धरण",
        "status_External Source Error": "बाहरी स्रोत त्रुटि",
        "status_Not Indexed / Not Found": "अनुक्रमित नहीं / नहीं मिला",
    },
    "marathi": {
        "title": "उद्धरण अखंडता अहवाल",
        "summary_verified": "सत्यापित",
        "summary_partial": "आंशिक जुळणी",
        "summary_mismatch": "विसंगती",
        "summary_fabrication": "बनावट",
        "summary_unverified": "असत्यापित",
        "full_filing_text": "संपूर्ण दाखल मजकूर",
        "citations_found": "या दाखलात आढळलेले उद्धरण",
        "court": "न्यायालय",
        "date": "दिनांक",
        "status": "स्थिती",
        "identity": "ओळख",
        "proposition": "विधान",
        "na": "उपलब्ध नाही",
        "adjusted_note": "* पूर्वीच्या मानवी सुधारणेनुसार समायोजित",
        "originally": "मूळतः",
        "status_Verified": "सत्यापित",
        "status_Partial Match": "आंशिक जुळणी",
        "status_Mismatch": "विसंगती",
        "status_Possible Fabrication": "संभाव्य बनावट",
        "status_Unverified Citation": "असत्यापित उद्धरण",
        "status_External Source Error": "बाह्य स्रोत त्रुटी",
        "status_Not Indexed / Not Found": "अनुक्रमित नाही / सापडले नाही",
    },
    "bengali": {
        "title": "উদ্ধৃতি সততা প্রতিবেদন",
        "summary_verified": "যাচাইকৃত",
        "summary_partial": "আংশিক মিল",
        "summary_mismatch": "অমিল",
        "summary_fabrication": "জালিয়াতি",
        "summary_unverified": "অযাচাইকৃত",
        "full_filing_text": "সম্পূর্ণ ফাইলিং পাঠ্য",
        "citations_found": "এই ফাইলিংয়ে পাওয়া উদ্ধৃতি",
        "court": "আদালত",
        "date": "তারিখ",
        "status": "অবস্থা",
        "identity": "পরিচয়",
        "proposition": "বক্তব্য",
        "na": "উপলব্ধ নয়",
        "adjusted_note": "* পূর্ববর্তী মানব সংশোধন থেকে সামঞ্জস্যকৃত",
        "originally": "মূলত",
        "status_Verified": "যাচাইকৃত",
        "status_Partial Match": "আংশিক মিল",
        "status_Mismatch": "অমিল",
        "status_Possible Fabrication": "সম্ভাব্য জালিয়াতি",
        "status_Unverified Citation": "অযাচাইকৃত উদ্ধৃতি",
        "status_External Source Error": "বাহ্যিক উৎস ত্রুটি",
        "status_Not Indexed / Not Found": "সূচিবদ্ধ নয় / পাওয়া যায়নি",
    },
    "tamil": {
        "title": "மேற்கோள் நேர்மை அறிக்கை",
        "summary_verified": "சரிபார்க்கப்பட்டது",
        "summary_partial": "பகுதி பொருத்தம்",
        "summary_mismatch": "பொருந்தவில்லை",
        "summary_fabrication": "கட்டுக்கதை",
        "summary_unverified": "சரிபார்க்கப்படவில்லை",
        "full_filing_text": "முழு தாக்கல் உரை",
        "citations_found": "இந்த தாக்கலில் கண்டறியப்பட்ட மேற்கோள்கள்",
        "court": "நீதிமன்றம்",
        "date": "தேதி",
        "status": "நிலை",
        "identity": "அடையாளம்",
        "proposition": "கூற்று",
        "na": "கிடைக்கவில்லை",
        "adjusted_note": "* முந்தைய மனித திருத்தத்திலிருந்து சரிசெய்யப்பட்டது",
        "originally": "முதலில்",
        "status_Verified": "சரிபார்க்கப்பட்டது",
        "status_Partial Match": "பகுதி பொருத்தம்",
        "status_Mismatch": "பொருந்தவில்லை",
        "status_Possible Fabrication": "சாத்தியமான கட்டுக்கதை",
        "status_Unverified Citation": "சரிபார்க்கப்படாத மேற்கோள்",
        "status_External Source Error": "வெளிப்புற மூல பிழை",
        "status_Not Indexed / Not Found": "அட்டவணைப்படுத்தப்படவில்லை / கிடைக்கவில்லை",
    },
    "telugu": {
        "title": "సైటేషన్ సమగ్రత నివేదిక",
        "summary_verified": "ధృవీకరించబడింది",
        "summary_partial": "పాక్షిక సరిపోలిక",
        "summary_mismatch": "అసమతుల్యత",
        "summary_fabrication": "కల్పితం",
        "summary_unverified": "ధృవీకరించబడలేదు",
        "full_filing_text": "పూర్తి ఫైలింగ్ టెక్స్ట్",
        "citations_found": "ఈ ఫైలింగ్‌లో కనుగొనబడిన సైటేషన్‌లు",
        "court": "న్యాయస్థానం",
        "date": "తేదీ",
        "status": "స్థితి",
        "identity": "గుర్తింపు",
        "proposition": "ప్రతిపాదన",
        "na": "అందుబాటులో లేదు",
        "adjusted_note": "* మునుపటి మానవ సవరణ నుండి సర్దుబాటు చేయబడింది",
        "originally": "వాస్తవానికి",
        "status_Verified": "ధృవీకరించబడింది",
        "status_Partial Match": "పాక్షిక సరిపోలిక",
        "status_Mismatch": "అసమతుల్యత",
        "status_Possible Fabrication": "సంభావ్య కల్పితం",
        "status_Unverified Citation": "ధృవీకరించని సైటేషన్",
        "status_External Source Error": "బాహ్య మూల లోపం",
        "status_Not Indexed / Not Found": "సూచికలో లేదు / కనుగొనబడలేదు",
    },
    "kannada": {
        "title": "ಉಲ್ಲೇಖ ಸಮಗ್ರತೆ ವರದಿ",
        "summary_verified": "ಪರಿಶೀಲಿಸಲಾಗಿದೆ",
        "summary_partial": "ಭಾಗಶಃ ಹೊಂದಾಣಿಕೆ",
        "summary_mismatch": "ಹೊಂದಾಣಿಕೆಯಾಗುತ್ತಿಲ್ಲ",
        "summary_fabrication": "ಸೃಷ್ಟಿಸಲಾದ",
        "summary_unverified": "ಪರಿಶೀಲಿಸದ",
        "full_filing_text": "ಪೂರ್ಣ ಫೈಲಿಂಗ್ ಪಠ್ಯ",
        "citations_found": "ಈ ಫೈಲಿಂಗ್‌ನಲ್ಲಿ ಕಂಡುಬಂದ ಉಲ್ಲೇಖಗಳು",
        "court": "ನ್ಯಾಯಾಲಯ",
        "date": "ದಿನಾಂಕ",
        "status": "ಸ್ಥಿತಿ",
        "identity": "ಗುರುತು",
        "proposition": "ಪ್ರತಿಪಾದನೆ",
        "na": "ಲಭ್ಯವಿಲ್ಲ",
        "adjusted_note": "* ಹಿಂದಿನ ಮಾನವ ತಿದ್ದುಪಡಿಯಿಂದ ಹೊಂದಿಸಲಾಗಿದೆ",
        "originally": "ಮೂಲತಃ",
        "status_Verified": "ಪರಿಶೀಲಿಸಲಾಗಿದೆ",
        "status_Partial Match": "ಭಾಗಶಃ ಹೊಂದಾಣಿಕೆ",
        "status_Mismatch": "ಹೊಂದಾಣಿಕೆಯಾಗುತ್ತಿಲ್ಲ",
        "status_Possible Fabrication": "ಸಂಭಾವ್ಯ ಸೃಷ್ಟಿ",
        "status_Unverified Citation": "ಪರಿಶೀಲಿಸದ ಉಲ್ಲೇಖ",
        "status_External Source Error": "ಬಾಹ್ಯ ಮೂಲ ದೋಷ",
        "status_Not Indexed / Not Found": "ಸೂಚಿಕರಿಸಿಲ್ಲ / ಸಿಗಲಿಲ್ಲ",
    },
    "gujarati": {
        "title": "ટાંકણ અખંડિતતા અહેવાલ",
        "summary_verified": "ચકાસાયેલ",
        "summary_partial": "આંશિક મેળ",
        "summary_mismatch": "અસંગતતા",
        "summary_fabrication": "બનાવટી",
        "summary_unverified": "અચકાસાયેલ",
        "full_filing_text": "સંપૂર્ણ ફાઇલિંગ લખાણ",
        "citations_found": "આ ફાઇલિંગમાં મળેલા ટાંકણો",
        "court": "અદાલત",
        "date": "તારીખ",
        "status": "સ્થિતિ",
        "identity": "ઓળખ",
        "proposition": "વિધાન",
        "na": "ઉપલબ્ધ નથી",
        "adjusted_note": "* અગાઉના માનવ સુધારાથી સમાયોજિત",
        "originally": "મૂળરૂપે",
        "status_Verified": "ચકાસાયેલ",
        "status_Partial Match": "આંશિક મેળ",
        "status_Mismatch": "અસંગતતા",
        "status_Possible Fabrication": "સંભવિત બનાવટ",
        "status_Unverified Citation": "અચકાસાયેલ ટાંકણ",
        "status_External Source Error": "બાહ્ય સ્રોત ભૂલ",
        "status_Not Indexed / Not Found": "અનુક્રમિત નથી / મળ્યું નથી",
    },
    "malayalam": {
        "title": "ഉദ്ധരണി സത്യസന്ധത റിപ്പോർട്ട്",
        "summary_verified": "പരിശോധിച്ചുറപ്പിച്ചത്",
        "summary_partial": "ഭാഗിക പൊരുത്തം",
        "summary_mismatch": "പൊരുത്തക്കേട്",
        "summary_fabrication": "കെട്ടിച്ചമച്ചത്",
        "summary_unverified": "പരിശോധിക്കാത്തത്",
        "full_filing_text": "പൂർണ്ണ ഫയലിംഗ് വാചകം",
        "citations_found": "ഈ ഫയലിംഗിൽ കണ്ടെത്തിയ ഉദ്ധരണികൾ",
        "court": "കോടതി",
        "date": "തീയതി",
        "status": "നില",
        "identity": "തിരിച്ചറിയൽ",
        "proposition": "പ്രസ്താവന",
        "na": "ലഭ്യമല്ല",
        "adjusted_note": "* മുൻ മനുഷ്യ തിരുത്തലിൽ നിന്ന് ക്രമീകരിച്ചത്",
        "originally": "യഥാർത്ഥത്തിൽ",
        "status_Verified": "പരിശോധിച്ചുറപ്പിച്ചത്",
        "status_Partial Match": "ഭാഗിക പൊരുത്തം",
        "status_Mismatch": "പൊരുത്തക്കേട്",
        "status_Possible Fabrication": "സാധ്യമായ കെട്ടിച്ചമയ്ക്കൽ",
        "status_Unverified Citation": "പരിശോധിക്കാത്ത ഉദ്ധരണി",
        "status_External Source Error": "ബാഹ്യ ഉറവിട പിശക്",
        "status_Not Indexed / Not Found": "സൂചികയിലില്ല / കണ്ടെത്തിയില്ല",
    },
    "punjabi": {
        "title": "ਹਵਾਲਾ ਇਕਸਾਰਤਾ ਰਿਪੋਰਟ",
        "summary_verified": "ਪੁਸ਼ਟੀ ਕੀਤੀ",
        "summary_partial": "ਅੰਸ਼ਕ ਮੇਲ",
        "summary_mismatch": "ਬੇਮੇਲ",
        "summary_fabrication": "ਮਨਘੜਤ",
        "summary_unverified": "ਅਪੁਸ਼ਟ",
        "full_filing_text": "ਪੂਰਾ ਫਾਈਲਿੰਗ ਪਾਠ",
        "citations_found": "ਇਸ ਫਾਈਲਿੰਗ ਵਿੱਚ ਮਿਲੇ ਹਵਾਲੇ",
        "court": "ਅਦਾਲਤ",
        "date": "ਮਿਤੀ",
        "status": "ਸਥਿਤੀ",
        "identity": "ਪਛਾਣ",
        "proposition": "ਬਿਆਨ",
        "na": "ਉਪਲਬਧ ਨਹੀਂ",
        "adjusted_note": "* ਪਿਛਲੀ ਮਨੁੱਖੀ ਸੁਧਾਈ ਤੋਂ ਅਨੁਕੂਲਿਤ",
        "originally": "ਮੂਲ ਰੂਪ ਵਿੱਚ",
        "status_Verified": "ਪੁਸ਼ਟੀ ਕੀਤੀ",
        "status_Partial Match": "ਅੰਸ਼ਕ ਮੇਲ",
        "status_Mismatch": "ਬੇਮੇਲ",
        "status_Possible Fabrication": "ਸੰਭਾਵਿਤ ਮਨਘੜਤ",
        "status_Unverified Citation": "ਅਪੁਸ਼ਟ ਹਵਾਲਾ",
        "status_External Source Error": "ਬਾਹਰੀ ਸਰੋਤ ਗਲਤੀ",
        "status_Not Indexed / Not Found": "ਸੂਚੀਬੱਧ ਨਹੀਂ / ਨਹੀਂ ਮਿਲਿਆ",
    },
    "odia": {
        "title": "ଉଦ୍ଧୃତି ସଚ୍ଚୋଟତା ରିପୋର୍ଟ",
        "summary_verified": "ଯାଞ୍ଚିତ",
        "summary_partial": "ଆଂଶିକ ମେଳ",
        "summary_mismatch": "ଅସଙ୍ଗତି",
        "summary_fabrication": "ମନଗଢ଼ା",
        "summary_unverified": "ଅଯାଞ୍ଚିତ",
        "full_filing_text": "ସମ୍ପୂର୍ଣ୍ଣ ଫାଇଲିଂ ପାଠ୍ୟ",
        "citations_found": "ଏହି ଫାଇଲିଂରେ ମିଳିଥିବା ଉଦ୍ଧୃତି",
        "court": "ନ୍ୟାୟାଳୟ",
        "date": "ତାରିଖ",
        "status": "ସ୍ଥିତି",
        "identity": "ପରିଚୟ",
        "proposition": "ବକ୍ତବ୍ୟ",
        "na": "ଉପଲବ୍ଧ ନାହିଁ",
        "adjusted_note": "* ପୂର୍ବ ମାନବ ସଂଶୋଧନରୁ ସାମଞ୍ଜସ୍ୟ କରାଯାଇଛି",
        "originally": "ମୂଳତଃ",
        "status_Verified": "ଯାଞ୍ଚିତ",
        "status_Partial Match": "ଆଂଶିକ ମେଳ",
        "status_Mismatch": "ଅସଙ୍ଗତି",
        "status_Possible Fabrication": "ସମ୍ଭାବ୍ୟ ମନଗଢ଼ା",
        "status_Unverified Citation": "ଅଯାଞ୍ଚିତ ଉଦ୍ଧୃତି",
        "status_External Source Error": "ବାହ୍ୟ ଉତ୍ସ ତ୍ରୁଟି",
        "status_Not Indexed / Not Found": "ସୂଚୀକୃତ ନୁହେଁ / ମିଳିଲା ନାହିଁ",
    },
}

# Fonts able to render each language's script (see backend/assets/fonts/).
# 'en' and 'hinglish' stay on core Helvetica (Latin-1) -- no embedding needed.
PDF_FONTS = {
    "hindi": "NotoSansDevanagari",
    "marathi": "NotoSansDevanagari",
    "bengali": "NotoSansBengali",
    "tamil": "NotoSansTamil",
    "telugu": "NotoSansTelugu",
    "kannada": "NotoSansKannada",
    "gujarati": "NotoSansGujarati",
    "malayalam": "NotoSansMalayalam",
    "punjabi": "NotoSansGurmukhi",
    "odia": "NotoSansOriya",
}


def get_labels(lang: str) -> dict:
    return PDF_LABELS.get(lang, _EN)


def get_status_label(lang: str, status_value: str) -> str:
    labels = get_labels(lang)
    return labels.get(f"status_{status_value}", status_value)
